// generate-question — dashboard-deployable bundle (auto-generated by scripts/flatten-functions.mjs)
// Source of truth: supabase/functions/generate-question/index.ts + _shared modules.
import { createClient } from "npm:@supabase/supabase-js@2.45.4";
import type { SupabaseClient, User } from "npm:@supabase/supabase-js@2.45.4";

// ===== inlined _shared/cors.ts =====
/**
 * CORS headers attached to EVERY response (success, failure, and preflight).
 * verify_jwt is disabled in config.toml so the OPTIONS preflight (which
 * carries no Authorization header) reaches the function; each function then
 * verifies the JWT itself via requireUser().
 */
export const corsHeaders: Record<string, string> = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, GET, OPTIONS",
  "Access-Control-Max-Age": "86400",
};

/** Standard response for the CORS preflight request. */
export function handleOptions(): Response {
  return new Response("ok", { status: 200, headers: corsHeaders });
}

// ===== inlined _shared/response.ts =====
/**
 * Uniform JSON envelope used by every edge function:
 *   success: { success: true,  data: <object>, error: null }
 *   failure: { success: false, data: null,     error: { code, message } }
 */

export interface ApiError {
  code: string;
  message: string;
}

export interface ApiEnvelope<T> {
  success: boolean;
  data: T | null;
  error: ApiError | null;
}

/** Structured error carrying an envelope code and an HTTP status. */
export class HttpError extends Error {
  readonly code: string;
  readonly status: number;

  constructor(code: string, message: string, status: number) {
    super(message);
    this.name = "HttpError";
    this.code = code;
    this.status = status;
  }
}

const jsonHeaders: Record<string, string> = {
  ...corsHeaders,
  "Content-Type": "application/json",
};

/** 200 success envelope. */
export function ok<T>(data: T): Response {
  const body: ApiEnvelope<T> = { success: true, data, error: null };
  return new Response(JSON.stringify(body), {
    status: 200,
    headers: jsonHeaders,
  });
}

/** Failure envelope with an appropriate HTTP status code. */
export function fail(code: string, message: string, status = 400): Response {
  const body: ApiEnvelope<never> = {
    success: false,
    data: null,
    error: { code, message },
  };
  return new Response(JSON.stringify(body), { status, headers: jsonHeaders });
}

/**
 * Convert any thrown value into a failure Response.
 * HttpError keeps its code/status; everything else becomes INTERNAL_ERROR
 * (logged server-side, never leaked to the client).
 */
export function failFromError(err: unknown, context: string): Response {
  if (err instanceof HttpError) {
    if (err.status >= 500) console.error(`[${context}]`, err.code, err.message);
    return fail(err.code, err.message, err.status);
  }
  console.error(`[${context}] unhandled error:`, err);
  return fail("INTERNAL_ERROR", "An unexpected error occurred", 500);
}

// ===== inlined _shared/supabase.ts =====
function requireEnv(name: string): string {
  const value = Deno.env.get(name);
  if (!value) {
    throw new HttpError("CONFIG_ERROR", `${name} is not configured`, 500);
  }
  return value;
}

/**
 * RLS-scoped client: anon key + the caller's Authorization header.
 * Every query runs as the calling user, so Row Level Security applies.
 */
export function createUserClient(req: Request): SupabaseClient {
  const url = requireEnv("SUPABASE_URL");
  const anonKey = requireEnv("SUPABASE_ANON_KEY");
  return createClient(url, anonKey, {
    global: {
      headers: { Authorization: req.headers.get("Authorization") ?? "" },
    },
    auth: { persistSession: false, autoRefreshToken: false },
  });
}

/**
 * Service-role client: BYPASSES Row Level Security.
 * Use ONLY where the spec requires it (admin verification/actions, storage
 * downloads that were already authorized in code, profile lookups by email).
 */
export function createServiceClient(): SupabaseClient {
  const url = requireEnv("SUPABASE_URL");
  const serviceKey = requireEnv("SUPABASE_SERVICE_ROLE_KEY");
  return createClient(url, serviceKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
}

interface PostgrestLikeError {
  message: string;
  code?: string;
}

interface PostgrestLikeResult<T> {
  data: T | null;
  error: PostgrestLikeError | null;
}

/**
 * Unwrap a supabase-js result, mapping common PostgREST failures onto the
 * envelope error codes.
 */
export function unwrap<T>(result: PostgrestLikeResult<T>, what: string): T {
  if (result.error) {
    if (result.error.code === "42501") {
      throw new HttpError("FORBIDDEN", `Not allowed: ${what}`, 403);
    }
    if (result.error.code === "PGRST116") {
      throw new HttpError("NOT_FOUND", `${what}: not found`, 404);
    }
    throw new HttpError("DB_ERROR", `${what}: ${result.error.message}`, 500);
  }
  return result.data as T;
}

// ===== inlined _shared/auth.ts =====
export type UserRole = "candidate" | "interviewer" | "admin";
export type UserStatus = "active" | "suspended";

export interface Profile {
  id: string;
  full_name: string;
  email: string;
  avatar_url: string | null;
  role: UserRole;
  status: UserStatus;
  experience_years: number | null;
}

export interface AuthContext {
  user: User;
  userClient: SupabaseClient;
}

/**
 * Verify the caller's JWT (config.toml sets verify_jwt = false so that the
 * CORS preflight succeeds; THIS is the mandatory auth gate for every request).
 * Returns the verified user plus an RLS-scoped client.
 */
export async function requireUser(req: Request): Promise<AuthContext> {
  const authHeader = req.headers.get("Authorization") ?? "";
  const token = authHeader.replace(/^Bearer\s+/i, "").trim();
  if (!token) {
    throw new HttpError("UNAUTHORIZED", "Missing Authorization bearer token", 401);
  }

  const userClient = createUserClient(req);
  const { data, error } = await userClient.auth.getUser(token);
  if (error || !data?.user) {
    throw new HttpError("UNAUTHORIZED", "Invalid or expired token", 401);
  }
  return { user: data.user, userClient };
}

/**
 * Load the caller's profile and enforce that the account is active.
 * Throws 404 PROFILE_NOT_FOUND / 403 ACCOUNT_SUSPENDED.
 */
export async function getProfile(
  client: SupabaseClient,
  userId: string,
): Promise<Profile> {
  const { data, error } = await client
    .from("profiles")
    .select("id, full_name, email, avatar_url, role, status, experience_years")
    .eq("id", userId)
    .maybeSingle();

  if (error) {
    throw new HttpError("DB_ERROR", `Failed to load profile: ${error.message}`, 500);
  }
  if (!data) {
    throw new HttpError("PROFILE_NOT_FOUND", "No profile exists for this user", 404);
  }
  const profile = data as Profile;
  if (profile.status !== "active") {
    throw new HttpError("ACCOUNT_SUSPENDED", "This account is suspended", 403);
  }
  return profile;
}

/** Throw 403 FORBIDDEN unless the profile has one of the allowed roles. */
export function requireRole(profile: Profile, roles: readonly UserRole[]): void {
  if (!roles.includes(profile.role)) {
    throw new HttpError(
      "FORBIDDEN",
      `This action requires one of the roles: ${roles.join(", ")}`,
      403,
    );
  }
}

// ===== inlined _shared/rateLimit.ts =====
/**
 * In-memory sliding-window rate limiter.
 *
 * LIMITATION: state lives in a module-level Map, i.e. it is PER EDGE-RUNTIME
 * INSTANCE. Supabase may run several isolates (and cold-starts reset the map),
 * so the effective limit is approximate. In production, back this with a
 * durable shared store (Redis/Upstash, or a Postgres table keyed by
 * user+function+window) for a hard guarantee. It still stops the common case:
 * a single client hammering one warm instance.
 *
 * Defaults: 30 requests/min per user per function; AI-backed functions use
 * 15/min. Callers return 429 RATE_LIMITED when this returns false.
 */

const WINDOW_DEFAULT_MS = 60_000;
const LIMIT_DEFAULT = 30;

/** Per-AI-function default (heavier upstream cost). */
export const AI_RATE_LIMIT = 15;

const buckets = new Map<string, number[]>();

/**
 * Returns true when the call is allowed, false when the key exceeded
 * `limit` calls within the sliding `windowMs` window.
 */
export function checkRateLimit(
  key: string,
  limit: number = LIMIT_DEFAULT,
  windowMs: number = WINDOW_DEFAULT_MS,
): boolean {
  const now = Date.now();
  const cutoff = now - windowMs;
  const timestamps = (buckets.get(key) ?? []).filter((t) => t > cutoff);

  if (timestamps.length >= limit) {
    buckets.set(key, timestamps);
    return false;
  }

  timestamps.push(now);
  buckets.set(key, timestamps);

  // Opportunistic cleanup so the map cannot grow unbounded on a warm instance.
  if (buckets.size > 10_000) {
    for (const [k, ts] of buckets) {
      if (ts.every((t) => t <= cutoff)) buckets.delete(k);
    }
  }
  return true;
}

// ===== inlined _shared/validate.ts =====
/**
 * Tiny request validators. Every failure throws
 * HttpError("VALIDATION_ERROR", ..., 400).
 */

const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/;

function invalid(message: string): HttpError {
  return new HttpError("VALIDATION_ERROR", message, 400);
}

/** Parse the JSON request body into a plain object. */
export async function readJsonBody(
  req: Request,
): Promise<Record<string, unknown>> {
  let parsed: unknown;
  try {
    parsed = await req.json();
  } catch {
    throw invalid("Request body must be valid JSON");
  }
  if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw invalid("Request body must be a JSON object");
  }
  return parsed as Record<string, unknown>;
}

export interface StringOptions {
  min?: number;
  max?: number;
}

export function requireString(
  value: unknown,
  field: string,
  opts: StringOptions = {},
): string {
  if (typeof value !== "string") throw invalid(`${field} must be a string`);
  const trimmed = value.trim();
  const min = opts.min ?? 1;
  if (trimmed.length < min) {
    throw invalid(`${field} must be at least ${min} character(s)`);
  }
  if (opts.max !== undefined && trimmed.length > opts.max) {
    throw invalid(`${field} must be at most ${opts.max} characters`);
  }
  return trimmed;
}

export function optionalString(
  value: unknown,
  field: string,
  opts: StringOptions = {},
): string | undefined {
  if (value === undefined || value === null || value === "") return undefined;
  return requireString(value, field, opts);
}

export function requireNumberInRange(
  value: unknown,
  field: string,
  min: number,
  max: number,
): number {
  const num = typeof value === "string" && value.trim() !== ""
    ? Number(value)
    : value;
  if (typeof num !== "number" || !Number.isFinite(num)) {
    throw invalid(`${field} must be a number`);
  }
  if (num < min || num > max) {
    throw invalid(`${field} must be between ${min} and ${max}`);
  }
  return num;
}

export function optionalNumberInRange(
  value: unknown,
  field: string,
  min: number,
  max: number,
): number | undefined {
  if (value === undefined || value === null || value === "") return undefined;
  return requireNumberInRange(value, field, min, max);
}

export function requireEnum<T extends string>(
  value: unknown,
  field: string,
  allowed: readonly T[],
): T {
  if (typeof value !== "string" || !allowed.includes(value as T)) {
    throw invalid(`${field} must be one of: ${allowed.join(", ")}`);
  }
  return value as T;
}

export function optionalEnum<T extends string>(
  value: unknown,
  field: string,
  allowed: readonly T[],
): T | undefined {
  if (value === undefined || value === null || value === "") return undefined;
  return requireEnum(value, field, allowed);
}

export function requireUuid(value: unknown, field: string): string {
  if (typeof value !== "string" || !UUID_RE.test(value)) {
    throw invalid(`${field} must be a valid UUID`);
  }
  return value.toLowerCase();
}

export function optionalUuid(value: unknown, field: string): string | undefined {
  if (value === undefined || value === null || value === "") return undefined;
  return requireUuid(value, field);
}

export function optionalBoolean(
  value: unknown,
  field: string,
): boolean | undefined {
  if (value === undefined || value === null) return undefined;
  if (typeof value !== "boolean") throw invalid(`${field} must be a boolean`);
  return value;
}

/** Missing value -> []; present value must be an array of strings. */
export function optionalStringArray(
  value: unknown,
  field: string,
  maxItems = 100,
  maxItemLength = 20_000,
): string[] {
  if (value === undefined || value === null) return [];
  if (!Array.isArray(value)) throw invalid(`${field} must be an array of strings`);
  if (value.length > maxItems) {
    throw invalid(`${field} must contain at most ${maxItems} items`);
  }
  return value.map((item, i) => {
    if (typeof item !== "string") {
      throw invalid(`${field}[${i}] must be a string`);
    }
    return item.length > maxItemLength ? item.slice(0, maxItemLength) : item;
  });
}

export function requireEmail(value: unknown, field: string): string {
  const email = requireString(value, field, { min: 5, max: 320 });
  if (!EMAIL_RE.test(email)) throw invalid(`${field} must be a valid email address`);
  return email;
}

export function isUuid(value: string): boolean {
  return UUID_RE.test(value);
}

// ===== inlined _shared/audit.ts =====
/**
 * Best-effort audit logging - never throws, never fails the request.
 * With a user client the audit_logs INSERT policy requires
 * user_id === auth.uid(); with the service client any user_id is accepted.
 */
export async function logAudit(
  client: SupabaseClient,
  userId: string | null,
  action: string,
  resourceType?: string | null,
  resourceId?: string | null,
  metadata?: Record<string, unknown>,
): Promise<void> {
  try {
    const { error } = await client.from("audit_logs").insert({
      user_id: userId,
      action,
      resource_type: resourceType ?? null,
      resource_id: resourceId ?? null,
      metadata: metadata ?? {},
    });
    if (error) {
      console.error(`logAudit(${action}) insert failed:`, error.message);
    }
  } catch (err) {
    console.error(`logAudit(${action}) threw:`, err);
  }
}

// ===== inlined _shared/ai/types.ts =====
/**
 * Provider-agnostic AI contracts shared by every AI-backed edge function.
 * All scores are numbers on a 0-100 scale.
 */

export type InterviewAIType = "hr" | "technical" | "behavioral" | "mixed";
export type Difficulty = "easy" | "medium" | "hard" | "expert";

export interface GenerateQuestionParams {
  role: string;
  experienceYears?: number;
  interviewType: InterviewAIType;
  difficulty: Difficulty;
  category?: string;
  questionNumber: number;
  totalQuestions: number;
  previousQuestions: string[];
  previousAnswers: string[];
  resumeSummary?: string;
}

export interface GeneratedQuestion {
  question: string;
  category: string;
  question_type: string;
  expected_topics: string[];
  time_limit_seconds: number;
  is_follow_up: boolean;
  difficulty: string;
}

export interface AudioMetadata {
  duration_seconds?: number;
  speaking_pace_wpm?: number;
  filler_word_count?: number;
}

export interface VideoMetadata {
  eye_contact_indicator?: number;
  face_presence_ratio?: number;
  head_movement_level?: string;
  expression_variation?: string;
}

export interface AnalyzeAnswerParams {
  question: string;
  answer: string;
  transcript?: string;
  jobRole: string;
  experienceYears?: number;
  questionType?: string;
  expectedTopics?: string[];
  audioMetadata?: AudioMetadata;
  videoMetadata?: VideoMetadata;
}

export interface AnswerAnalysis {
  relevance: number;
  technical_accuracy: number;
  communication: number;
  clarity: number;
  structure: number;
  confidence_indicator: number;
  speaking_pace: number | null;
  filler_word_count: number | null;
  strengths: string[];
  weaknesses: string[];
  recommendations: string[];
  summary: string;
}

export interface ComponentScores {
  technical: number | null;
  communication: number | null;
  confidence: number | null;
  problem_solving: number | null;
  behavioral: number | null;
  mcq: number | null;
  overall: number | null;
}

export interface SummaryParams {
  jobRole: string;
  interviewType: string;
  analyses: Array<Partial<AnswerAnalysis> & { overall_score?: number | null }>;
  scores: ComponentScores;
}

export type Recommendation = "strong_hire" | "hire" | "consider" | "no_hire";

export interface ResultSummary {
  summary: string;
  strengths: string[];
  weaknesses: string[];
  recommendation: Recommendation;
}

export interface AIProvider {
  name: string;
  generateQuestion(p: GenerateQuestionParams): Promise<GeneratedQuestion>;
  generateFollowUp(p: GenerateQuestionParams): Promise<GeneratedQuestion>;
  analyzeAnswer(p: AnalyzeAnswerParams): Promise<AnswerAnalysis>;
  generateSummary(p: SummaryParams): Promise<ResultSummary>;
  generateReport(p: { report: unknown }): Promise<string>;
}

// ===== inlined _shared/ai/prompts.ts =====
/**
 * Prompt builders + robust JSON parsing/normalization shared by all providers,
 * so OpenAI and Anthropic stay thin transport adapters.
 */

/** Non-negotiable assessment rules baked into every system prompt. */
export const SAFETY_RULES = `Non-negotiable rules:
- All score dimensions use a 0-100 scale.
- Act as a realistic professional interviewer/assessor: reward specific, structured, accurate, relevant content; penalize vague, off-topic, or empty content. Do not inflate scores.
- NEVER infer or mention race, ethnicity, religion, health, disability, sexuality, personality traits, mental health, honesty, or criminality.
- Any commentary about video or facial signals must describe only observable behavior in neutral language (e.g. "eye gaze frequently moved away from the camera"), never claims about emotion, honesty, or competence based on appearance.
- confidence_indicator is a composite of observable communication signals (steady pacing, few filler words, decisive phrasing); it is NOT a psychological measurement or personality judgment.`;

function truncate(text: string, max: number): string {
  return text.length > max ? `${text.slice(0, max)} [...truncated]` : text;
}

// ---------------------------------------------------------------------------
// Question generation
// ---------------------------------------------------------------------------

export function questionSystemPrompt(): string {
  return `You are an experienced, professional job interviewer conducting a structured interview. You ask exactly one question at a time, pitched to the role, interview type, difficulty, and the candidate's experience level.

Behavior:
- Question 1 of an interview is a warm opener (an introduction / "walk me through your background" style question) tailored to the role.
- Never repeat or closely paraphrase any previously asked question.
- When explicitly instructed to ask a follow-up, reference a concrete detail from the candidate's most recent answer.
- Adapt difficulty: if previous answers are strong and detailed, step depth up gradually; if they are weak, keep difficulty steady and supportive.
- Never ask illegal or discriminatory interview questions (age, family plans, religion, health, etc.).

${SAFETY_RULES}

Respond ONLY with one JSON object, no prose, exactly this shape:
{"question": string, "category": string, "question_type": "behavioral" | "hr" | "technical" | "situational", "expected_topics": string[], "time_limit_seconds": number (60-600), "is_follow_up": boolean, "difficulty": "easy" | "medium" | "hard" | "expert"}`;
}

export function questionUserPrompt(
  p: GenerateQuestionParams,
  followUp: boolean,
): string {
  const previousQuestions = p.previousQuestions.length
    ? `Questions already asked:\n${p.previousQuestions
        .map((q, i) => `${i + 1}. ${truncate(q, 400)}`)
        .join("\n")}`
    : "No questions have been asked yet.";

  const previousAnswers = p.previousAnswers.length
    ? `Candidate's answers so far (same order):\n${p.previousAnswers
        .map((a, i) => `${i + 1}. ${truncate(a, 700)}`)
        .join("\n")}`
    : null;

  let instruction: string;
  if (followUp) {
    instruction =
      'Ask a FOLLOW-UP question that explicitly references a concrete detail from the candidate\'s most recent answer. Set "is_follow_up": true.';
  } else if (p.questionNumber === 1) {
    instruction =
      'This is the opening question: ask a warm introduction question tailored to the role. Set "is_follow_up": false.';
  } else {
    instruction =
      'Ask the next fresh question (not a follow-up). Set "is_follow_up": false. Roughly 30% of questions after the second may be follow-ups, but for THIS one produce a new question while adapting difficulty to the quality of previous answers.';
  }

  const lines: Array<string | null> = [
    `Role being interviewed for: ${p.role}`,
    p.experienceYears !== undefined
      ? `Candidate experience: ${p.experienceYears} year(s)`
      : null,
    `Interview type: ${p.interviewType}`,
    `Target difficulty: ${p.difficulty}`,
    p.category ? `Category focus: ${p.category}` : null,
    `This is question ${p.questionNumber} of ${p.totalQuestions}.`,
    p.resumeSummary
      ? `Resume summary: ${truncate(p.resumeSummary, 2000)}`
      : null,
    previousQuestions,
    previousAnswers,
    instruction,
  ];
  return lines.filter((l): l is string => l !== null).join("\n\n");
}

// ---------------------------------------------------------------------------
// Answer analysis
// ---------------------------------------------------------------------------

export function analysisSystemPrompt(): string {
  return `You are an expert interview assessor evaluating one candidate answer. Score each dimension 0-100:
- relevance: does the answer address the question that was actually asked?
- technical_accuracy: factual/technical correctness of the content (for non-technical questions, score the soundness and credibility of the content).
- communication: overall communication effectiveness (vocabulary, flow, coherence).
- clarity: how easy the answer is to follow.
- structure: logical organization (e.g. STAR for behavioral answers).
- confidence_indicator: composite of observable communication signals only.

Scoring anchors: 0-25 empty or off-topic; 26-50 weak or vague; 51-70 adequate; 71-85 good and specific; 86-100 excellent, specific, and well structured.

If audio metrics (speaking pace, filler word count) are provided, you may refine them; otherwise return them as null. Only comment on provided video metrics using neutral, observable language.

${SAFETY_RULES}

Respond ONLY with one JSON object, no prose, exactly this shape:
{"relevance": number, "technical_accuracy": number, "communication": number, "clarity": number, "structure": number, "confidence_indicator": number, "speaking_pace": number | null, "filler_word_count": number | null, "strengths": string[] (max 4), "weaknesses": string[] (max 4), "recommendations": string[] (max 4), "summary": string (2-3 neutral sentences)}`;
}

export function analysisUserPrompt(p: AnalyzeAnswerParams): string {
  const answerText = p.transcript?.trim() || p.answer;
  const lines: Array<string | null> = [
    `Job role: ${p.jobRole}`,
    p.experienceYears !== undefined
      ? `Candidate experience: ${p.experienceYears} year(s)`
      : null,
    p.questionType ? `Question type: ${p.questionType}` : null,
    `Interview question: ${truncate(p.question, 1500)}`,
    p.expectedTopics && p.expectedTopics.length
      ? `Topics a strong answer would cover: ${p.expectedTopics.join(", ")}`
      : null,
    `Candidate's answer${p.transcript ? " (speech transcript)" : ""}:\n${truncate(answerText, 8000)}`,
    p.audioMetadata
      ? `Audio metrics: ${JSON.stringify(p.audioMetadata)}`
      : null,
    p.videoMetadata
      ? `Video metrics (observable signals only): ${JSON.stringify(p.videoMetadata)}`
      : null,
  ];
  return lines.filter((l): l is string => l !== null).join("\n\n");
}

// ---------------------------------------------------------------------------
// Interview result summary
// ---------------------------------------------------------------------------

export function summarySystemPrompt(): string {
  return `You write the final assessment summary of a completed interview based on per-answer analyses and aggregate component scores.

Recommendation bands (anchor to the overall score): >= 85 "strong_hire"; 70-84 "hire"; 55-69 "consider"; below 55 "no_hire".

${SAFETY_RULES}

Respond ONLY with one JSON object, no prose, exactly this shape:
{"summary": string (3-5 professional sentences about demonstrated skills and gaps), "strengths": string[] (max 5), "weaknesses": string[] (max 5), "recommendation": "strong_hire" | "hire" | "consider" | "no_hire"}`;
}

export function summaryUserPrompt(p: SummaryParams): string {
  const analyses = p.analyses.slice(0, 25).map((a, i) => ({
    n: i + 1,
    overall_score: a.overall_score ?? null,
    relevance: a.relevance ?? null,
    technical_accuracy: a.technical_accuracy ?? null,
    communication: a.communication ?? null,
    structure: a.structure ?? null,
    strengths: (a.strengths ?? []).slice(0, 3),
    weaknesses: (a.weaknesses ?? []).slice(0, 3),
    summary: a.summary ? truncate(a.summary, 400) : null,
  }));
  return [
    `Job role: ${p.jobRole}`,
    `Interview type: ${p.interviewType}`,
    `Aggregate component scores (0-100, null = not assessed): ${JSON.stringify(p.scores)}`,
    `Per-answer analyses: ${JSON.stringify(analyses)}`,
  ].join("\n\n");
}

// ---------------------------------------------------------------------------
// Report narrative
// ---------------------------------------------------------------------------

export function reportSystemPrompt(): string {
  return `You write a professional executive narrative (150-250 words, plain text, 2-3 paragraphs) for an interview assessment report. Base it strictly on the structured report data provided; do not invent facts, and keep the tone neutral and professional.

${SAFETY_RULES}

Respond ONLY with one JSON object, no prose, exactly this shape:
{"narrative": string}`;
}

export function reportUserPrompt(p: { report: unknown }): string {
  return `Structured interview report data:\n${truncate(JSON.stringify(p.report), 12000)}`;
}

// ---------------------------------------------------------------------------
// Robust parsing + normalization
// ---------------------------------------------------------------------------

/** Parse a JSON object out of a model reply (tolerates fences/extra prose). */
export function parseJsonObject(raw: string): Record<string, unknown> {
  let text = raw.trim();
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/i);
  if (fenced) text = fenced[1].trim();

  const candidates = [text];
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  if (start >= 0 && end > start) candidates.push(text.slice(start, end + 1));

  for (const candidate of candidates) {
    try {
      const value: unknown = JSON.parse(candidate);
      if (value !== null && typeof value === "object" && !Array.isArray(value)) {
        return value as Record<string, unknown>;
      }
    } catch {
      // try next candidate
    }
  }
  throw new Error("AI response did not contain a parseable JSON object");
}

/** Coerce to a number clamped to [0, 100]; fallback (default 50) if invalid. */
export function clampScore(value: unknown, fallback = 50): number {
  const num = typeof value === "string" ? Number(value) : value;
  if (typeof num !== "number" || !Number.isFinite(num)) return fallback;
  return Math.min(100, Math.max(0, Math.round(num * 10) / 10));
}

function optionalNumber(
  value: unknown,
  min: number,
  max: number,
): number | null {
  const num = typeof value === "string" ? Number(value) : value;
  if (typeof num !== "number" || !Number.isFinite(num)) return null;
  return Math.min(max, Math.max(min, num));
}

function toStringArray(value: unknown, maxItems: number): string[] {
  if (!Array.isArray(value)) return [];
  return value
    .filter((item): item is string => typeof item === "string" && item.trim() !== "")
    .slice(0, maxItems)
    .map((item) => item.trim());
}

const QUESTION_TYPES = [
  "behavioral",
  "hr",
  "technical",
  "situational",
  "coding",
  "mcq",
] as const;
const DIFFICULTIES = ["easy", "medium", "hard", "expert"] as const;

export function normalizeGeneratedQuestion(
  obj: Record<string, unknown>,
  p: GenerateQuestionParams,
): GeneratedQuestion {
  const question = typeof obj.question === "string" ? obj.question.trim() : "";
  if (!question) throw new Error("AI provider did not return a question");

  const fallbackType = p.interviewType === "mixed" ? "technical" : p.interviewType;
  const questionType =
    typeof obj.question_type === "string" &&
      (QUESTION_TYPES as readonly string[]).includes(obj.question_type)
      ? obj.question_type
      : fallbackType;

  const difficulty =
    typeof obj.difficulty === "string" &&
      (DIFFICULTIES as readonly string[]).includes(obj.difficulty)
      ? obj.difficulty
      : p.difficulty;

  const category =
    typeof obj.category === "string" && obj.category.trim() !== ""
      ? obj.category.trim()
      : (p.category ?? p.role);

  const timeLimit = optionalNumber(obj.time_limit_seconds, 30, 900);

  return {
    question,
    category,
    question_type: questionType,
    expected_topics: toStringArray(obj.expected_topics, 8),
    time_limit_seconds: Math.round(timeLimit ?? 180),
    is_follow_up: obj.is_follow_up === true,
    difficulty,
  };
}

export function normalizeAnswerAnalysis(
  obj: Record<string, unknown>,
): AnswerAnalysis {
  const fillers = optionalNumber(obj.filler_word_count, 0, 10_000);
  return {
    relevance: clampScore(obj.relevance),
    technical_accuracy: clampScore(obj.technical_accuracy),
    communication: clampScore(obj.communication),
    clarity: clampScore(obj.clarity),
    structure: clampScore(obj.structure),
    confidence_indicator: clampScore(obj.confidence_indicator),
    speaking_pace: optionalNumber(obj.speaking_pace, 0, 400),
    filler_word_count: fillers === null ? null : Math.round(fillers),
    strengths: toStringArray(obj.strengths, 5),
    weaknesses: toStringArray(obj.weaknesses, 5),
    recommendations: toStringArray(obj.recommendations, 5),
    summary: typeof obj.summary === "string" ? obj.summary.trim() : "",
  };
}

const RECOMMENDATIONS = ["strong_hire", "hire", "consider", "no_hire"] as const;

export function normalizeResultSummary(
  obj: Record<string, unknown>,
): ResultSummary {
  const recommendation =
    typeof obj.recommendation === "string" &&
      (RECOMMENDATIONS as readonly string[]).includes(obj.recommendation)
      ? (obj.recommendation as Recommendation)
      : "consider";
  return {
    summary: typeof obj.summary === "string" ? obj.summary.trim() : "",
    strengths: toStringArray(obj.strengths, 6),
    weaknesses: toStringArray(obj.weaknesses, 6),
    recommendation,
  };
}

// ===== inlined _shared/ai/openai.ts =====
/**
 * Base URL is configurable so any OpenAI-compatible provider works —
 * including free tiers: Groq (https://api.groq.com/openai/v1), Google
 * Gemini (https://generativelanguage.googleapis.com/v1beta/openai),
 * OpenRouter (https://openrouter.ai/api/v1). Defaults to OpenAI itself.
 */
export function openAIBaseUrl(): string {
  return (Deno.env.get("OPENAI_BASE_URL") ?? "https://api.openai.com/v1").replace(/\/+$/, "");
}

const OPENAI_REQUEST_TIMEOUT_MS = 60_000;

interface OpenAIChatResponse {
  choices?: Array<{ message?: { content?: string | null } }>;
}

export class OpenAIProvider implements AIProvider {
  readonly name = "openai";
  private readonly apiKey: string;
  private readonly model: string;
  private readonly chatUrl: string;

  constructor(apiKey: string) {
    this.apiKey = apiKey;
    this.model = Deno.env.get("AI_MODEL") ?? "gpt-4o-mini";
    this.chatUrl = `${openAIBaseUrl()}/chat/completions`;
  }

  private async chatJson(
    system: string,
    user: string,
    temperature: number,
  ): Promise<Record<string, unknown>> {
    const response = await fetch(this.chatUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${this.apiKey}`,
      },
      body: JSON.stringify({
        model: this.model,
        temperature,
        response_format: { type: "json_object" },
        messages: [
          { role: "system", content: system },
          { role: "user", content: user },
        ],
      }),
      signal: AbortSignal.timeout(OPENAI_REQUEST_TIMEOUT_MS),
    });

    if (!response.ok) {
      const detail = (await response.text()).slice(0, 500);
      throw new Error(`OpenAI API error ${response.status}: ${detail}`);
    }

    const payload = (await response.json()) as OpenAIChatResponse;
    const content = payload.choices?.[0]?.message?.content;
    if (!content) throw new Error("OpenAI returned an empty completion");
    return parseJsonObject(content);
  }

  async generateQuestion(p: GenerateQuestionParams): Promise<GeneratedQuestion> {
    const obj = await this.chatJson(
      questionSystemPrompt(),
      questionUserPrompt(p, false),
      0.7,
    );
    return normalizeGeneratedQuestion(obj, p);
  }

  async generateFollowUp(p: GenerateQuestionParams): Promise<GeneratedQuestion> {
    const obj = await this.chatJson(
      questionSystemPrompt(),
      questionUserPrompt(p, true),
      0.7,
    );
    return { ...normalizeGeneratedQuestion(obj, p), is_follow_up: true };
  }

  async analyzeAnswer(p: AnalyzeAnswerParams): Promise<AnswerAnalysis> {
    const obj = await this.chatJson(
      analysisSystemPrompt(),
      analysisUserPrompt(p),
      0.2,
    );
    return normalizeAnswerAnalysis(obj);
  }

  async generateSummary(p: SummaryParams): Promise<ResultSummary> {
    const obj = await this.chatJson(
      summarySystemPrompt(),
      summaryUserPrompt(p),
      0.3,
    );
    return normalizeResultSummary(obj);
  }

  async generateReport(p: { report: unknown }): Promise<string> {
    const obj = await this.chatJson(
      reportSystemPrompt(),
      reportUserPrompt(p),
      0.4,
    );
    return typeof obj.narrative === "string" && obj.narrative.trim() !== ""
      ? obj.narrative.trim()
      : JSON.stringify(obj);
  }
}

// ===== inlined _shared/ai/anthropic.ts =====
const ANTHROPIC_MESSAGES_URL = "https://api.anthropic.com/v1/messages";
const ANTHROPIC_VERSION = "2023-06-01";
const ANTHROPIC_REQUEST_TIMEOUT_MS = 60_000;

interface AnthropicContentBlock {
  type: string;
  text?: string;
}

interface AnthropicMessagesResponse {
  content?: AnthropicContentBlock[];
}

export class AnthropicProvider implements AIProvider {
  readonly name = "anthropic";
  private readonly apiKey: string;
  private readonly model: string;

  constructor(apiKey: string) {
    this.apiKey = apiKey;
    this.model = Deno.env.get("AI_MODEL") ?? "claude-sonnet-5";
  }

  private async completeJson(
    system: string,
    user: string,
    temperature: number,
    maxTokens = 2000,
  ): Promise<Record<string, unknown>> {
    const response = await fetch(ANTHROPIC_MESSAGES_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": this.apiKey,
        "anthropic-version": ANTHROPIC_VERSION,
      },
      body: JSON.stringify({
        model: this.model,
        max_tokens: maxTokens,
        temperature,
        system,
        messages: [{ role: "user", content: user }],
      }),
      signal: AbortSignal.timeout(ANTHROPIC_REQUEST_TIMEOUT_MS),
    });

    if (!response.ok) {
      const detail = (await response.text()).slice(0, 500);
      throw new Error(`Anthropic API error ${response.status}: ${detail}`);
    }

    const payload = (await response.json()) as AnthropicMessagesResponse;
    const text = payload.content
      ?.filter((block) => block.type === "text" && typeof block.text === "string")
      .map((block) => block.text as string)
      .join("\n");
    if (!text) throw new Error("Anthropic returned an empty completion");
    return parseJsonObject(text);
  }

  async generateQuestion(p: GenerateQuestionParams): Promise<GeneratedQuestion> {
    const obj = await this.completeJson(
      questionSystemPrompt(),
      questionUserPrompt(p, false),
      0.7,
    );
    return normalizeGeneratedQuestion(obj, p);
  }

  async generateFollowUp(p: GenerateQuestionParams): Promise<GeneratedQuestion> {
    const obj = await this.completeJson(
      questionSystemPrompt(),
      questionUserPrompt(p, true),
      0.7,
    );
    return { ...normalizeGeneratedQuestion(obj, p), is_follow_up: true };
  }

  async analyzeAnswer(p: AnalyzeAnswerParams): Promise<AnswerAnalysis> {
    const obj = await this.completeJson(
      analysisSystemPrompt(),
      analysisUserPrompt(p),
      0.2,
    );
    return normalizeAnswerAnalysis(obj);
  }

  async generateSummary(p: SummaryParams): Promise<ResultSummary> {
    const obj = await this.completeJson(
      summarySystemPrompt(),
      summaryUserPrompt(p),
      0.3,
    );
    return normalizeResultSummary(obj);
  }

  async generateReport(p: { report: unknown }): Promise<string> {
    const obj = await this.completeJson(
      reportSystemPrompt(),
      reportUserPrompt(p),
      0.4,
    );
    return typeof obj.narrative === "string" && obj.narrative.trim() !== ""
      ? obj.narrative.trim()
      : JSON.stringify(obj);
  }
}

// ===== inlined _shared/ai/index.ts =====
/**
 * Resolve the configured AI provider:
 *  - AI_PROVIDER=openai|anthropic selects explicitly (needs its key);
 *  - otherwise auto-detect by whichever of OPENAI_API_KEY / ANTHROPIC_API_KEY
 *    exists (OpenAI wins when both are set);
 *  - null when nothing is configured. Callers respond with a
 *    503 AI_NOT_CONFIGURED envelope in that case.
 */
export function getAIProvider(): AIProvider | null {
  const preference = (Deno.env.get("AI_PROVIDER") ?? "").trim().toLowerCase();
  const openaiKey = Deno.env.get("OPENAI_API_KEY");
  const anthropicKey = Deno.env.get("ANTHROPIC_API_KEY");

  if (preference === "openai") {
    return openaiKey ? new OpenAIProvider(openaiKey) : null;
  }
  if (preference === "anthropic") {
    return anthropicKey ? new AnthropicProvider(anthropicKey) : null;
  }
  if (openaiKey) return new OpenAIProvider(openaiKey);
  if (anthropicKey) return new AnthropicProvider(anthropicKey);
  return null;
}

// ===== function: generate-question =====
/**
 * POST generate-question
 * Generates the next adaptive interview question (or a follow-up ~30% of the
 * time after question 2 when the previous answer has substance).
 */
Deno.serve(async (req: Request): Promise<Response> => {
  if (req.method === "OPTIONS") return handleOptions();

  try {
    if (req.method !== "POST") {
      throw new HttpError("METHOD_NOT_ALLOWED", "Use POST", 405);
    }

    const { user, userClient } = await requireUser(req);
    await getProfile(userClient, user.id); // enforces active account

    if (!checkRateLimit(`generate-question:${user.id}`, AI_RATE_LIMIT)) {
      throw new HttpError("RATE_LIMITED", "Too many requests - try again in a minute", 429);
    }

    const body = await readJsonBody(req);
    const role = requireString(body.role, "role", { min: 2, max: 120 });
    const interviewType = requireEnum(body.interview_type, "interview_type", [
      "hr",
      "technical",
      "behavioral",
      "mixed",
    ] as const);
    const difficulty = requireEnum(body.difficulty, "difficulty", [
      "easy",
      "medium",
      "hard",
      "expert",
    ] as const);
    const questionNumber = requireNumberInRange(body.question_number, "question_number", 1, 100);
    const totalQuestions = requireNumberInRange(body.total_questions, "total_questions", 1, 100);
    const previousQuestions = optionalStringArray(body.previous_questions, "previous_questions", 100, 2000);
    const previousAnswers = optionalStringArray(body.previous_answers, "previous_answers", 100, 20_000);
    const experienceYears = optionalNumberInRange(body.experience_years, "experience_years", 0, 60);
    const category = optionalString(body.category, "category", { max: 120 });
    const resumeSummary = optionalString(body.resume_summary, "resume_summary", { max: 6000 });
    const interviewId = optionalUuid(body.interview_id, "interview_id");

    // If tied to an interview, the RLS-scoped select proves the caller is a
    // participant (creator/candidate/admin) - non-participants see no row.
    if (interviewId) {
      const { data: interview, error } = await userClient
        .from("interviews")
        .select("id")
        .eq("id", interviewId)
        .maybeSingle();
      if (error) throw new HttpError("DB_ERROR", error.message, 500);
      if (!interview) {
        throw new HttpError("NOT_FOUND", "Interview not found or you are not a participant", 404);
      }
    }

    const provider = getAIProvider();
    if (!provider) {
      throw new HttpError(
        "AI_NOT_CONFIGURED",
        "No AI provider is configured. Set OPENAI_API_KEY or ANTHROPIC_API_KEY (and optionally AI_PROVIDER).",
        503,
      );
    }

    const params: GenerateQuestionParams = {
      role,
      experienceYears,
      interviewType,
      difficulty,
      category,
      questionNumber,
      totalQuestions,
      previousQuestions,
      previousAnswers,
      resumeSummary,
    };

    // Adaptive behavior: first question is always an introduction (handled in
    // the prompt); after Q2, ~30% of questions become follow-ups when the last
    // answer has enough substance to probe.
    const lastAnswer = previousAnswers[previousAnswers.length - 1] ?? "";
    const askFollowUp =
      questionNumber > 2 &&
      lastAnswer.trim().split(/\s+/).filter(Boolean).length >= 12 &&
      Math.random() < 0.3;

    const question = askFollowUp
      ? await provider.generateFollowUp(params)
      : await provider.generateQuestion(params);

    return ok(question);
  } catch (err) {
    return failFromError(err, "generate-question");
  }
});
