import { LegalLayout } from "@/components/layout/LegalLayout";

export default function Terms() {
  return (
    <LegalLayout title="Terms of Service">
      <p>
        These terms govern your use of Testify. By creating an account you agree to them. If you use Testify on behalf of
        an organization, you confirm you are authorized to bind that organization.
      </p>

      <h2>Accounts and roles</h2>
      <ul>
        <li>You must provide accurate information and keep your credentials secure.</li>
        <li>Candidate and interviewer accounts are self-service; administrator access is granted only by an existing administrator.</li>
        <li>You are responsible for activity under your account.</li>
      </ul>

      <h2>Acceptable use</h2>
      <ul>
        <li>Do not attempt to access data that is not yours, probe security controls, or interfere with other users' assessments.</li>
        <li>Do not upload unlawful content or content you lack rights to.</li>
        <li>Interviewers must use assessment monitoring and AI analysis lawfully — including complying with local employment and biometric-privacy law — and must not represent AI indicators as psychological measurements.</li>
        <li>Do not use automated means to complete monitored assessments on a candidate's behalf.</li>
      </ul>

      <h2>AI-generated content</h2>
      <p>
        Interview questions, analysis, and summaries may be generated by AI systems. They are decision-support signals,
        not decisions. Hiring outcomes remain the responsibility of the humans running the process, and AI output should
        always be reviewed alongside the transcript and your own judgment.
      </p>

      <h2>Suspension and termination</h2>
      <p>
        Administrators may suspend accounts that violate these terms. You may stop using the service at any time and may
        request deletion of your data as described in the Privacy Policy.
      </p>

      <h2>Disclaimers</h2>
      <p>
        Testify is provided "as is". To the maximum extent permitted by law, we disclaim implied warranties and are not
        liable for indirect or consequential damages. Nothing in these terms limits liability that cannot lawfully be
        limited.
      </p>

      <h2>Changes</h2>
      <p>We may update these terms; material changes will be announced in-app. Continued use after changes means acceptance.</p>
    </LegalLayout>
  );
}
